### ISSUE TITLE
UV Sensor not working in the demo

### ISSUE THREAD

**Issue by raz0rsedge1975** [swimos/matrixOne#1]
First of all I'd like to thank you for this awesome piece of hardware (voice; creator)
I think this repo is a bit outdated since I can't find https://github.com/swimit/flightinfo.git
and also no gauges.html

The UV sensor is not working in the demo, why is that?

**Comment by scottswim** [comment]
Thanks for letting us know. The README is now updated with proper information and the UV bug in the node bridge is now fixed. Let us know if you run across any other issues.
