### ISSUE TITLE
Prevent Sensors Demo from showing floating point numbers like -1.7e+2

### ISSUE THREAD

**Issue by raz0rsedge1975** [swimos/matrixOne#2]
Hi there,

this is not a "fault" because the sensors are working properly but I am stuck here while trying to process the sensor data. Depending on the values several sensors like **Air Pressure** or **Yaw** are shown up as floating point numbers formatted with e+5 or e+2. 
I would suggest to show up to 4 decimals (-0.0004 or 1.2001) and to be able to process the values,
suppress the potency's - maybe just cut off some decimals or round below 4. digit

A very minor issue of the sensors.html is a spelling mistake in both **Tempurature** readings.

Thanks for this awesome realtime demo,
I wish you a Merry Christmas!

**Comment by scottswim** [comment]
Hi again,

Thanks for pointing out the typo. Spelling can be hard sometimes. Also thanks for the suggestions, I have implemented them on the sensors page.

Have a great New Years!
